name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: grain-sandbox
    steps:
    - name: Run tests
      run: |
        sudo rm -f /etc/apt/sources.list.d/hashicorp.list || true
        sudo apt-get update || true
        sudo apt-get install -y python3-pexpect
        python3 -m unittest discover -s tests
