apiVersion: v1
kind: Pod
metadata:
  name: {{NAME}}
  labels:
    app: swebench
spec:
  restartPolicy: Never
  containers:
  - name: swebench
    image: {{IMAGE}}
    volumeMounts:
    - name: replay-script-vol
      mountPath: /replay.py
      subPath: replay.py
  volumes:
  - name: replay-script-vol
    configMap:
      name: replay-script
