apiVersion: v1
kind: Pod
metadata:
  name: {{NAME}}
  labels:
    app: swebench
spec:
  restartPolicy: Never
  containers:
  - name: swebench
    image: {{IMAGE}}
    imagePullPolicy: Always
    resources:
      limits:
        memory: "4Gi"
        cpu: "12"
      requests:
        cpu: "10m"
        memory: "10Mi"
    env:
    - name: USE_GCP_CACHE
      value: "1"
    - name: INSTANCE_ID
      value: "{{INSTANCE_ID}}"
    - name: PAGER
      value: "cat"
    - name: GIT_PAGER
      value: "cat"
    - name: PIP_INDEX_URL_TEMPLATE
      value: "{{PIP_INDEX_URL_TEMPLATE}}"
    - name: PIP_TRUSTED_HOST
      value: "{{PIP_TRUSTED_HOST}}"
