apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUpMM2c1YlpSTzVBM1NDU0lrdnFvUnN3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05ESTFPRE0yWldZdE5EUTRNeTAwWlRReExXSTFOekF0T0RWa05UVTRNMkkwWVRaagpNQ0FYRFRJMk1EY3hOakUxTWpRME5sb1lEekl3TlRZd056QTRNVFl5TkRRMldqQXZNUzB3S3dZRFZRUURFeVEwCk1qVTRNelpsWmkwME5EZ3pMVFJsTkRFdFlqVTNNQzA0TldRMU5UZ3pZalJoTm1Nd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDU0xnMUtabWFPR2wzTkZLTVdOYXBUdS9JcXQwVzRNWTRyQWxNbworYUJoWTB6cHdMMWtScDlQckppekJVQ3ZwUjJZcTdtdEJ1NWZwTXZwTE9GWkcvdURkYUtTcFJvTXVXeWozdDl1CnRCQ0hpR2tIRjBhenBzd1k1cG1ZdXlhZXRtN1VoUXpWUGs0Wk84NE5uVjVSZUtRRW1LZFhHNGVlSWRTRlIwaGMKKzlTaTQvN3hrcmtGK0pRYnVwSTlLYVdCanJCVXhoZ1lGSjZ0N0g5cllwSHVSanNodzY3clFWU1RaaUNyZzVFegoxclFOMW5ZT3RWSlRMMC9Nc2ppNnZxdndvTHhwa3ovbVAra2JLbFJxeXRid0VnWTE5cFdlc2ZyWGdZLzUzSDhmClM4NW81dVhjY2R2cWt1WGFnc2haV1h6dnV2L3RVY0MwOFZkQ24rN1lDOHkxRlpHMXhzeGlJWDNFYnlNZWdHOUoKZE1BNTQrdCtJbVB5dkpLSjVVNjRTMUZ5VVQ0T2dPWDZuYy8rWklPQk9ia0VScEIwbWVNR240ZzhYeU16cUo0bgpUTFY5eExBWTZEc1Jhb2E5RXErOGUzazN3UENHZGwrMXowRGMzY2traVlpWjk4NnovaUliSnBjMHNhME1FaHF2CnQ2bmxGRmFGc2l5K0NvQ2VWYWwzeVZsMm9kRUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUDhyZFYvSVdjVWgrQmpoZWp6RFdKRGNMb0RKTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQmtxeWVWLzR4QURoQTRhRHN2dzZzNzJGbUdCQ3A0WnN4N0hGaGcvbThjCjN6bGY1OFpXbTdmNzh5dVNHcXg2U2pYMEZOYlBXSU5MZnZpUEhqRHFkSUlTcjJHdUcxT09mMFJVbFB4cmkrUUcKZVY0c29naHFOT1UvSE9haytGOE9ySG8yaU5lL1gyUWhjcHptM0pES2czdmNnRk9ib1lKcjdlNjM0Z1VLMVlzaApRYUZMZzcyRWdFTnRKOWRIOU5jZ1M0U3AxUGJYNGJsd0xhajRTaUZMQ1Y5TnNDb2JvSEdzZXI0cDdpWDQzemxVCks3WG1EdDg5eGZLQm5NOERKNFlzTFRoR2ViQzJ3cEhxU3dVbVJHd2ZzYjhHSDcxQjhMbXlIWTFoSXo4aFYrOXoKTThqWGNWR2ZoOGRlSUhlbnRlVWtzOTFvZUNRZkN1TU9yNGpsNFFhWWFEQXJ5dDhaZXdjaWh2c0xrUkRnNnhzcQp4TXhHL0NRMEx2L3hoNHJhTnNUdllVKzJLbE5YdE9VdlIwL0NVRGRsTGk1OXg1QXFDV2xMK05QbmN6MUJNNzhSCm1JVnBrdnp3bWRaUk5ZOTJGQmFFRW56S2RGcHlkdTc1VEdqUkVsbG1GRS9FcVByTStRYkxyV2pKRk5UZ29NMjEKVVBoMWdINVYxK2xXQUt6akdtVGtteVU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.10.119.243
  name: gke_bsalmon-gke-dev_us-central1-b_sweperf-bench-2
contexts:
- context:
    cluster: gke_bsalmon-gke-dev_us-central1-b_sweperf-bench-2
    user: gke_bsalmon-gke-dev_us-central1-b_sweperf-bench-2
  name: gke_bsalmon-gke-dev_us-central1-b_sweperf-bench-2
current-context: gke_bsalmon-gke-dev_us-central1-b_sweperf-bench-2
kind: Config
preferences: {}
users:
- name: gke_bsalmon-gke-dev_us-central1-b_sweperf-bench-2
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --use_application_default_credentials
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      provideClusterInfo: true
