apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  labels:
    app: swebench
spec:
  restartPolicy: Never
  containers:
  - name: swebench
    image: us-central1-docker.pkg.dev/bsalmon-gke-dev/test-repo/sweperf:matplotlib__matplotlib-14623
    env:
    - name: PAGER
      value: "cat"
    - name: GIT_PAGER
      value: "cat"
