apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxTemplate
metadata:
  name: swe-bench-generic
spec:
  podTemplate:
    spec:
      containers:
      - name: sandbox
        image: us-central1-docker.pkg.dev/bsalmon-gke-dev/bsalmon-agentic-repo/swe-bench-base:latest
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      volumes:
      - name: workspace
        emptyDir: {}
